// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DerivativeUIClient is the client API for DerivativeUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DerivativeUIClient interface {
	// ListEngineSpecs returns a list of Derivative Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DerivativeUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type derivativeUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDerivativeUIClient(cc grpc.ClientConnInterface) DerivativeUIClient {
	return &derivativeUIClient{cc}
}

func (c *derivativeUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DerivativeUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DerivativeUI_ServiceDesc.Streams[0], "/v1.DerivativeUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &derivativeUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DerivativeUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type derivativeUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *derivativeUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *derivativeUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DerivativeUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DerivativeUIServer is the server API for DerivativeUI service.
// All implementations must embed UnimplementedDerivativeUIServer
// for forward compatibility
type DerivativeUIServer interface {
	// ListEngineSpecs returns a list of Derivative Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, DerivativeUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDerivativeUIServer()
}

// UnimplementedDerivativeUIServer must be embedded to have forward compatible implementations.
type UnimplementedDerivativeUIServer struct {
}

func (UnimplementedDerivativeUIServer) ListEngineSpecs(*ListEngineSpecsRequest, DerivativeUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedDerivativeUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDerivativeUIServer) mustEmbedUnimplementedDerivativeUIServer() {}

// UnsafeDerivativeUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DerivativeUIServer will
// result in compilation errors.
type UnsafeDerivativeUIServer interface {
	mustEmbedUnimplementedDerivativeUIServer()
}

func RegisterDerivativeUIServer(s grpc.ServiceRegistrar, srv DerivativeUIServer) {
	s.RegisterService(&DerivativeUI_ServiceDesc, srv)
}

func _DerivativeUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DerivativeUIServer).ListEngineSpecs(m, &derivativeUIListEngineSpecsServer{stream})
}

type DerivativeUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type derivativeUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *derivativeUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DerivativeUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DerivativeUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DerivativeUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DerivativeUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DerivativeUI_ServiceDesc is the grpc.ServiceDesc for DerivativeUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DerivativeUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DerivativeUI",
	HandlerType: (*DerivativeUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DerivativeUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _DerivativeUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "derivative-ui.proto",
}
